### ISSUE TITLE
Please tell me where these values are located I need to delete some of them

### ISSUE THREAD

**Issue by Papaswigs** [Starlynk1/IncognitoResurrected#2]
![temp](https://github.com/Starlynk1/IncognitoResurrected/assets/157286419/02970a4f-a43b-4f48-a9a7-1bde12247582)
Retail **WoW Version**
Retail, Classic, Classic Era
  
**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by Starlynk1** [comment]
You should be able to use the Delete a Profile dropdown and select which profile you want removed. Is that not working?

**Comment by Starlynk1** [comment]
I just tested some different char/class combos and it does appear that it is auto creating 'CharName - ServerName', 'Character Class' and 'ServerName' profiles. Since this is a resurrected addon, I will go through the profile code and see what I can do to stop it from making those extra ones that are not needed. Preferably I would rather have it just make a Default that is used by all characters and let the user have the choice of making additional profiles as needed.

Out of town currently, so won't be able to work on that until I get back to my main PC.

**Comment by Papaswigs** [comment]
> You should be able to use the Delete a Profile dropdown and select which profile you want removed. Is that not working?

No this does not remove them.

**Comment by Papaswigs** [comment]
> I just tested some different char/class combos and it does appear that it is auto creating 'CharName - ServerName', 'Character Class' and 'ServerName' profiles. Since this is a resurrected addon, I will go through the profile code and see what I can do to stop it from making those extra ones that are not needed. Preferably I would rather have it just make a Default that is used by all characters and let the user have the choice of making additional profiles as needed.
> 
> Out of town currently, so won't be able to work on that until I get back to my main PC.

Thank you, and this is an awesome add-on, thank you for your time and effort!

**Comment by Starlynk1** [comment]
Just pushed an update for this so all profiles use the Default as the actual default. It will still show Class, Server, and Name-Server but you shoudln't have those actually created as a profile that is retained. When you switch to another character, it should only show those for that class/name/server.
If you need a specific profile because you are with different guilds, you can create a new profile specific to that character/guild. I would use a Guild Name for the profile so its easier to remember what its for.

**Comment by Papaswigs** [comment]
Thank you, very much appreciated

**Comment by Starlynk1** [comment]
Closing, checked Ac3 and different options, it will always show additional options like class/name/server. No known way around this and other addons do that same thing when using a global default.
